import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { AuthProvider } from "@/contexts/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
  // children: React.PropsWithChildren;
}) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <AuthProvider>
        <body className={inter.className}>
          <AntdRegistry>{children}</AntdRegistry>
        </body>
      </AuthProvider>
    </html>
  );
}
